---

namespace: "drybjed"
name: "namespace2"
version: "1.0.0"
description: "Second test collection to fix bug in ansible-lint"

authors:
  - "Maciej Delmanowski <drybjed@gmail.com>"

repository: "https://github.com/drybjed/ansible-collections"
documentation: "https://github.com/drybjed/ansible-collections"
homepage: "https://drybjed.net/"
issues: "https://github.com/drybjed/ansible-collections"

readme: "README.md"

license:
  - "GPL-3.0-or-later"

tags:
  - "testing"

dependencies: {}
